package eu.trentorise.game.model
import eu.trentorise.game.core.Utility;
//declare any global variables here
global Utility utils;

rule "update_management_points"
when
    InputData( $management : data["management"])
    InputData( $manageComplexity : data["manageComplexity"])
    InputData( $revertPoints : data["revertPoints"])
    $pc : PointConcept(name == "management")
then
    utils.log("apply \'update management points\'");
    Double management = $management != null ? (Double) $management : 0;
    Double manageComplexity = $manageComplexity != null ? (Double) $manageComplexity : 0;
    if ($revertPoints != null) {
    	utils.log("revert management points");
    	if ($pc.getScore() - (management * manageComplexity) < 0) {
    		$pc.setScore(0d);
    	} else {
    		$pc.setScore($pc.getScore() - (management * manageComplexity));
    	}
    } else {
    	$pc.setScore($pc.getScore() + (management * manageComplexity));
    }
    update($pc);
end